import React from 'react';

import type { Metadata } from 'next';
import './globals.scss';
import { Provider } from '@/components/Provider/Provider.component';
import { Header } from '@/components/Header/Header.component';
import { Popup } from '@/ui/Popup/Popup.component';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header></Header>
          <main className="main">

            {children}
            <Popup />
          </main>
        </Provider>
      </body>
    </html>
  );
}
