import type { Metadata } from 'next'
import './globals.scss'
import { Provider } from '@/components/Provider/Provider.component'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="main">
          <Provider>
            {children}
          </Provider>
        </main>
      </body>
    </html>
  )
}
